🎨 Formatting

diff --git a/config/bash/bin/mov2mp4 b/config/bash/bin/mov2mp4
--- a/config/bash/bin/mov2mp4
+++ b/config/bash/bin/mov2mp4
@@ -1,27 +1,26 @@
-#!/usr/bin/env bash  
+#!/usr/bin/env bash
 
 case "$#" in
 2)
-    input="$1"
-    output="$2"
-    ;;
+	input="$1"
+	output="$2"
+	;;
 1)
-    input="$1"
-    echo "Output file: "
-    read output
-    ;;
+	input="$1"
+	echo "Output file: "
+	read output
+	;;
 0)
-    input=$(ls | fzf)
-    
-    echo "Output file: "
-    read output
-    ;;
+	input=$(ls | fzf)
+
+	echo "Output file: "
+	read output
+	;;
 esac
 
-if [ ! -f "$input" ]; then 
-    >&2 echo "error $input does not exist"
-    return
+if [ ! -f "$input" ]; then
+	>&2 echo "error $input does not exist"
+	return
 fi
 
 ffmpeg -i "$input" -vcodec h264 -acodec aac "$output".mp4
-
